version: "3"
services:
  validator_4:
    image: ankrnetwork/bas-template-bsc:devel
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x49c0f7c8c11a4c80dc6449efe1010bb166818da8"
      - "--miner.etherbase=0x49c0f7c8c11a4c80dc6449efe1010bb166818da8"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@${BOOTNODE}:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=17243"
    volumes:
      - "../genesis.json:/datadir/genesis.json"
      - "../keystore:/datadir/keystore"
      - "../password.txt:/datadir/password.txt"
      - "./datadir/validator_4:/datadir/geth"
    restart: always

  validator_5:
    image: ankrnetwork/bas-template-bsc:devel
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x8e1ea6eaa09c3b40f4a51fcd056a031870a0549a"
      - "--miner.etherbase=0x8e1ea6eaa09c3b40f4a51fcd056a031870a0549a"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@${BOOTNODE}:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=17243"
    volumes:
      - "../genesis.json:/datadir/genesis.json"
      - "../keystore:/datadir/keystore"
      - "../password.txt:/datadir/password.txt"
      - "./datadir/validator:/datadir/geth"
    restart: always
